### ISSUE TITLE
Compiled version

### ISSUE THREAD

**Issue by AnReZa** [svgdotjs/svg.filter.js#29]
Would you please provide a pre-compiled version for developers, who only use simple HTML/JS without any fancy tools? Most of the other SVG.js plugins provide a simple dist folder with a pre-compiled file in it.

**Comment by Fuzzyma** [comment]
You can download the latest release as zip here: https://github.com/svgdotjs/svg.filter.js/releases/tag/3.0.2

The zip file contains all precompiled versions. Minified and unminified with a sourcemap.

**Comment by AnReZa** [comment]
@Fuzzyma Thank you very much! But there is a problem with the provided version:

> Uncaught TypeError: svg_js.utils.capitalize is not a function
>     at svg.filter.js:160
>     at Array.forEach (<anonymous>)
>     at svg.filter.js:159
>     at svg.filter.js:440

Any idea how to fix that?

**Comment by Fuzzyma** [comment]
Did you include svg.js before the plugin? If not, thats the mistake. 
But if so: Please provide your code which threw this error.

**Comment by Fuzzyma** [comment]
Yes the new version of svg.filter needs the new svg.js version. We are in the progress of updating all plugins. But draggable as well as selectize are not ported yet.

So you have to stay with svg.js v2 and use the old filter plugin, too. `npm install svg.filter.js` should give you a version compatible to svg.js v2 (with a dist folder holding the precompiled files).

You can see if something is ready for svg.js v3 if it is available under `@svgdotjs/packagename` in npm instead of `packagename`. e.g. `npm install @svgdotjs/svg.filter.js` vs `npm install `svg.filter.js`

**Comment by AnReZa** [comment]
Oh, thank you for the info. I've downgraded to the latest 2.x and now the strange issues seem to be gone.
