### ISSUE TITLE
Getting it to work with Parcel?

### ISSUE THREAD

**Issue by iLLucionist** [svgdotjs/svg.filter.js#37]
I cannot get svg.filter.js to work. According to Parcel and npm, `svg.filter.js` is installed.

At top, I have:
```
import React from 'react'
import SVG from 'svg.js'
import 'svg.filter.js'
```

**Note**: import `import '@svgdotjs/svg.filter.js'` also doesn't work for me, though it is installed and imported for as far as I can tell.. This gives the console error: `filter is not a function`.

Then, I draw a circle:
```
var circle = draw.circle(16).attr({
    fill: #f00,
    cx: 10,
    cy: 10
})
```

I then try to use `filter` to apply svg.filter.js effects:
```
circle.filter(function(add) {
    add.gaussianBlur(30)
})
```

This returns in console with error:
```
Unexpected value 30 parsing stdDeviation attribute.
```

Drop shadow also does not work. None of the examples work for me. Am I doing something wrong?

**Comment by Lange** [comment]
I am also experiencing this issue with Webpack.

**Comment by Lange** [comment]
My current theory is that the issue is happening because `svg.filter.js` is pulling in a _separate installation_ of `svg.js`. Therefore, its augmentations are being applied to an instance of `svg.js` which nothing else on the page is using. Evidence of this can be seen in the webpack output, which alludes to a separate installation of `svg.js` inside `@svgdotjs/svg.filter.js/node_modules`:

![image](https://user-images.githubusercontent.com/873012/63140892-12f5fd00-bfa9-11e9-975c-ec75c3e79f13.png)

**Comment by Lurow** [comment]
could it be that the svg.filter.js on npm still requires svg.js version 3.0.12 and is pulling a separate version when you're on v. 3.0.13?

I saw the change in the git repo but last npm push is a few months older.

**Comment by Fuzzyma** [comment]
But the ^ in front of the Version number should pull the newest version. Why isn't that working?

**Comment by Lurow** [comment]
@Fuzzyma because it seems the npm version has a fixed dep.version. I think your commit is not in the latest release (3.0.6) 
[Comparison](https://github.com/svgdotjs/svg.filter.js/compare/3.0.6...master)
